In [1]:
import pandas as pd

In [2]:
items_train = pd.read_csv("data/items_train.csv")
items_phase_1 = pd.read_csv("data/items_phase_1.csv")
task_1 = pd.read_csv("data/task_1.csv")

In [9]:
items_train.head()

,itemId,price,colorTagIdsString,departmentIds,brandEditionTagId,title,description,geo,label
0,692210,148.0,"230,232",['11'],NaN,Раница Rains 14480 Черен,NaN,bg,41599
1,943360,148.0,"230,232",['11'],NaN,Раница Rains,Rains Раница 14480 Черен,bg,41599
2,447879,179.9,230,['1'],NaN,Раница Rains Trail Cord Rolltop Backpack W3 в ...,Раница от колекция Rains. Моделът е направен о...,bg,41599
3,1169543,179.9,230,"['1', '11']",NaN,Раница Rains Trail Cord Rolltop Backpack W3 в ...,- Непромокаем модел.\n- Повишена водоустойчиво...,bg,41599
4,671883,1910.0,"230,232",['11'],NaN,Batoh Rains,Rains Batoh 14480 Černá,cz,41599

In [10]:
items_phase_1.head()

,itemId,price,colorTagIdsString,departmentIds,brandEditionTagId,title,description,geo
0,451136,69.90,"771,772",['11'],NaN,Δερμάτινη θήκη για κάρτες Tommy Hilfiger χρώμα...,Πορτοφόλι της κολεξιόν Tommy Hilfiger. Μοντέλο...,gr
1,281651,29.95,775,['1'],NaN,Cepure Billabong,Billabong Cepure Alta Rib EBJHA00115 Rozā,lv
2,206147,76.99,230,['1'],NaN,Čizme Badura,Badura Čizme FUNCHAL-2603 Crna,hr
3,716396,69.95,6449,['42'],NaN,Sandále Froddo,Sandále Froddo Keko G3150287-10 M Modrá,sk
4,55666,29.90,"232,780",['11'],NaN,Secrid - Novčanik,- RFID Protect - zaštita od elektroničke krađe...,hr

In [12]:
task_1

        item1    item2    item3    item4    item5
0      130622   292253   463442   483968  1253745
1       82627   388496   553738   638400   884327
2       46130   333489   644448   848154  1178149
3      150796   248537   742067  1206230  1280786
4       76610   196894   345145   620255   932761
...       ...      ...      ...      ...      ...
14995  155554   524218  1124026  1180971  1245961
14996    2182   142647   528017   744044   966164
14997  360650   831549   941406  1002011  1225666
14998  481664  1021759  1123392  1272187  1283135
14999  195576   292422   600227  1079960  1172304

[15000 rows x 5 columns]